version: '2.3'

mongodb:
  host: 127.0.0.1
  port: 27017
  database: test
  collection: test

dht:
  bootstrap:
    - "router.bittorrent.com:6881"
    - "router.utorrent.com:6881"
    - "dht.transmissionbt.com:6881"
